/*
 * Stepper_prg.c
 *
 *  Created on: Aug 3, 2026
 *      Author: Omar Desoky
 */


#include "../../LIB/STD_TYPES.h"
#include "../../MCAL/DIO/DIO_int.h"
#include "stepper_int.h"
#include <avr/delay.h>



void HSTEPPER_vInit()
{
	MDIO_vSetPinDir(STEPPER_PORT, STEPPER_PINK, DIO_OUTPUT);
	MDIO_vSetPinDir(STEPPER_PORT, STEPPER_BLUE, DIO_OUTPUT);
	MDIO_vSetPinDir(STEPPER_PORT, STEPPER_YELLOW, DIO_OUTPUT);
	MDIO_vSetPinDir(STEPPER_PORT, STEPPER_ORANGE, DIO_OUTPUT);
}

void HSTEPPER_vRotateCW(f64 A_f64StepDelay)
{
	// STEP 1
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_PINK ,DIO_HIGH);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_BLUE ,DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_YELLOW ,DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_ORANGE ,DIO_LOW);
	_delay_ms(A_f64StepDelay);
	//STEP2
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_PINK ,DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_BLUE ,DIO_HIGH);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_YELLOW ,DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_ORANGE ,DIO_LOW);
	_delay_ms(A_f64StepDelay);
	//STEP3
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_PINK ,DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_BLUE ,DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_YELLOW ,DIO_HIGH);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_ORANGE ,DIO_LOW);
	_delay_ms(A_f64StepDelay);
	//STEP4
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_PINK ,DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_BLUE ,DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_YELLOW ,DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_ORANGE ,DIO_HIGH);
	_delay_ms(A_f64StepDelay);

}
void HSTEPPER_vRotateCCW(f64 A_f64StepDelay)
{
	//STEP1
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_PINK ,DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_BLUE ,DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_YELLOW ,DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_ORANGE ,DIO_HIGH);
	_delay_ms(A_f64StepDelay);
	//STEP2
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_PINK ,DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_BLUE ,DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_YELLOW ,DIO_HIGH);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_ORANGE ,DIO_LOW);
	_delay_ms(A_f64StepDelay);
	//STEP3
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_PINK ,DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_BLUE ,DIO_HIGH);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_YELLOW ,DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_ORANGE ,DIO_LOW);
	_delay_ms(A_f64StepDelay);
	//STEP4
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_PINK ,DIO_HIGH);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_BLUE ,DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_YELLOW ,DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_ORANGE ,DIO_LOW);
	_delay_ms(A_f64StepDelay);

}

void HSTEPPER_vStop()
{
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_PINK ,DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_BLUE ,DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_YELLOW ,DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT,STEPPER_ORANGE ,DIO_LOW);
}


